#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx to serve custom html content
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure nginx to redirect /redirect_me to another page
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://github.com/Tashydaije permanent;' /etc/nginx/sites-available/default

# Start nginx
service nginx restart
