#!/usr/bin/env bash
# Installs and configures a load balancer using HAProxy

# Install and create apt repository for HAProxy
apt-get update
apt-get install --no-install-recommends software-properties-common -y
apt-get update # For the next line to work
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get install haproxy=2.8.\* -y

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
frontend web_frontend
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 54.237.35.186:80 check
    server web-02 52.91.120.61:80 check
EOF

# Restart HAProxy
service haproxy restart

# Enable HAProxy init script
update-rc.d haproxy defaults
