#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.
# FizzBuzz - multiple of 3 and 5
# Fizz - multiple of 3
# Buzz - multiple of 5
# Otherwise, displays the number

n=1
while [ $n -le 100 ];
do
	if [ $((n % 15)) == 0 ];
	then
		echo "FizzBuzz"
	elif [ $((n % 3)) == 0 ];
	then
		echo "Fizz"
	elif [ $((n % 5)) == 0 ];
	then
		echo "Buzz"
	else
		echo "$n"
	fi
	((n++))
done
