#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sed -i 's/user\s*root;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-enabled/default
nginx -s reload
